name: paw_and_love
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  group_radio_button: ^1.2.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  persistent_bottom_nav_bar: ^4.0.2
  dropdown_search: ^2.0.1
  syncfusion_flutter_datepicker: ^19.4.48
  sizer: ^2.0.15
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+9
  uuid: ^3.0.6
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  web_socket_channel: ^2.1.0
  url_launcher: ^6.0.20
  time_range_picker: ^2.1.0
  awesome_dialog: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  date_utils: ^0.2.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/json/
    - assets/fonts/
  
  fonts:
    - family: Montserrat_Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf  

    - family: Montserrat_Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf  

    - family: Montserrat_Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

